# Generated by Django 4.2.1 on 2023-06-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triangle", "0002_alter_person_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogTriangle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("POST", "Post"),
                            ("GET", "Get"),
                            ("PUT", "Put"),
                            ("DELETE", "Delete"),
                            ("PATCH", "Patch"),
                            ("BAD", "Bad"),
                        ],
                        default="BAD",
                        max_length=6,
                    ),
                ),
                ("path", models.TextField(default="-")),
                ("query", models.TextField(default="-")),
                ("body", models.TextField(default="-")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
