# Generated by Django 4.2.1 on 2023-06-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triangle", "0004_alter_logtriangle_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="logtriangle",
            name="request",
            field=models.JSONField(default="BAD"),
            preserve_default=False,
        ),
    ]
