# Generated by Django 4.2.1 on 2023-06-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triangle", "0005_logtriangle_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="logtriangle",
            name="bad_method",
            field=models.BooleanField(default=True),
        ),
    ]
