# Generated by Django 4.2.1 on 2023-06-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triangle", "0006_logtriangle_bad_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="logtriangle",
            name="response_status",
            field=models.IntegerField(default=200),
        ),
    ]
