# Generated by Django 4.2.1 on 2023-07-10 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookstore", "0003_alter_book_publisher"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["rating", "price"]},
        ),
    ]
