# Generated by Django 4.2.1 on 2023-06-23 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_city_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="exp_date",
            field=models.DateField(
                db_comment="Date when the product expires",
                default=django.utils.timezone.now,
            ),
        ),
    ]
